### ISSUE TITLE
Wrong value returned from r_fishers_exact

### ISSUE THREAD

**Issue by heathsc** [cpearce/fishers_exact#2]
Hello,

r_fishers_exact() (in src/R/fexact.c) is not returning the right value from fexact().   Depending on the value of the tails parameter, r_fishers_exact() either returns pre or prt when the tails parameter is 1 or 2 respectively.   However, fexact() does not return the 1 tailed p-value.  It either returns pre (the two sided p-value or the probability of the observed table or a more extreme table) or prt (the probability of the observed table alone). This can be seen from the documentation for fexact().   r_fishers_exact(), therefore, should only return pre as the two-sided p-value, while the tails parameter is redundant and should be removed.  This can be verified using R.  Using the first test example [1, 9, 11, 3] we get the following from R for the two sided, less and greater alternative options:

> fisher.test(m<-matrix(c(1,9,11,3),ncol=2),alternative="two.sided")$p.value
[1] 0.002759456
> fisher.test(m<-matrix(c(1,9,11,3),ncol=2),alternative="less")$p.value
[1] 0.001379728
> fisher.test(m<-matrix(c(1,9,11,3),ncol=2),alternative="greater")$p.value
[1] 0.9999663
>
It can be seen that the two sided results, 0.002759456, corresponds with the value given by r_fishers_exact() for tails==1.

On another note, r_fishers_exact only allows for 2x2 tables whereas fexact() can handle larger tables (within memory limits).  Could this limit be documented or relaxed?

Thanks,
Simon

**Comment by cpearce** [comment]
Thanks very much for taking the time to file an issue! I agree, I'm returning the wrong value here.

I probably misread the code comment on the C function my Rust functions calls.

I'll look at fixing this when I get some spare time, probably next week.

Be aware that I ended up not using this crate myself in our own research, as it was very slow. We ended up [writing our own fishers exact test approximation code](https://github.com/cpearce/riptree/blob/3be51b279633da0d85728c683fc634399a4fb6b2/src/fptree.rs#L253) (i.e. not using R's) backed by [a lookup table of logarithms](https://github.com/cpearce/riptree/blob/3be51b279633da0d85728c683fc634399a4fb6b2/src/main.rs#L234) for speed. If you're doing something intensive or working with contingency tables with large values, you might consider copying that code instead. I had been considering switching this crate to using that method instead, but never got around to it. The lookup table approach requires knowing the max value that will appear in the contingency table, which makes it a little awkward to generalize cleanly.

**Comment by heathsc** [comment]
I actually did more or less the same thing as the fexact code was too slow for what I wanted.  I still do the exact calculation but it is only for 2x2 and it has a table for the ln gamma values.  I would still argue that it is worth including fexact but maybe following the strategy in R that an optimized version for 2x2 tables is used and the full fexact code only used for larger tables.

Cheers,
Simon

**Comment by cpearce** [comment]
Thanks again for filing this issue. I've published a new version of fishers_exact which reports less, greater and two tails pvalues, and verified the test statistics against those produced by scipy. I removed the R code, and ported some new code to Rust, so the crate's code is much simpler pure Rust now. The new code handles 2x2 tables only, and I've documented that.
